### ISSUE TITLE
Error while installing !

### ISSUE THREAD

**Issue by NassarX** [laravel-notification-channels/pusher-push-notifications#15]
### Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - laravel-notification-channels/pusher-push-notifications 1.0.1 requires pusher/pusher-php-server 2.5.0-rc4 -> satisfiable by pusher/pusher-php-server[v2.5.0-rc4] but these conflict with your requirements or minimum-stability.

even after installing [Pusher PHP Library](https://github.com/pusher/pusher-http-php) ^2.6 
still get the same error message every time run 'composer require laravel-notification-channels/pusher-push-notifications'. any help ?

**Comment by TehCrucible** [comment]
I had the same issue. The problem is caused because this package depends currently depends on an RC version of the pusher-php-server package. By default your composer setup wont allow you to install RC packages due to the minimum stability setting.

Considering the pusher package is now stable at 2.6, it's a simple fix, the devs just need to require that version instead.  I'll try and submit a pull request later today.  In the meantime you can fix it yourself by adding the following code to your composer.json file:

```
    "repositories": [
        {
            "type": "package",
            "package": {
                "name": "laravel-notification-channels/pusher-push-notifications",
                "version": "1.0.1",
                "require": {
                    "pusher/pusher-php-server": "2.6.*"
                },
                "dist": {
                    "url": "https://github.com/laravel-notification-channels/pusher-push-notifications/archive/1.0.1.zip",
                    "type": "zip"
                }
            }
        }
    ],
```

then add `"laravel-notification-channels/pusher-push-notifications": "1.0.1"` to your require block and `composer update`.

Hope that helps.

**Comment by NassarX** [comment]
@TehCrucible thanks for replying but although with requiring `"pusher/pusher-php-server": "@dev"` still getting same error .

**Comment by NassarX** [comment]
Thanks to @TehCrucible for referring to RC version .
now it works with require  `"pusher/pusher-php-server": "2.5.0-rc4", `.
